apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: secure-app-k8
        image: stasim101/secure-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080